### ISSUE TITLE
React Dependency

### ISSUE THREAD

**Issue by chadams** [syranide/react-swf#11]
why is this package depend on a beta version of react? (^0.14.0-beta1) most people are still on react@0.13.3

**Comment by syranide** [comment]
@chadams React 0.13 is still supported by the previous version of ReactSWF (0.11), this should automatically be taken care of by `npm`. The explicit dependency on React 0.14 is because of breaking changes in React that needed to be addressed.

**Comment by syranide** [comment]
Hmm, I'll need to research this, but it seems like there's no solution to this that doesn't involve user interaction one way or another. I could release versions with pre-release dependency on React as pre-release too, but it seems to me that it only solves half the problem. Unless you yourself switch to new React versions immediately as they are released you still end up with the same problem of `npm` upgrading to the latest ReactSWF which is incompatible with your still older React dependency...

All input is appreciated. Intuitively pre-release makes sense then, and the remaining issues are simply the way of life with `npm`?

**Comment by syranide** [comment]
In the future I'll make sure to tag versions that depend on pre-release versions of React as pre-release too, but other than that I don't think there's much I can do here.

Closing, but feel free to reopen or comment.
