### ISSUE TITLE
call js function with context

### ISSUE THREAD

**Issue by tadjik1** [syranide/react-swf#12]
Hello. Thanks for great component!

I have a problem with calling js callback function in context of my parent component:

```
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';
import ReactSWF from 'react-swf';

import './style.sass';

class Player extends Component {
    static propTypes = {
        url: PropTypes.string.isRequired,
        style: PropTypes.shape({
            position: PropTypes.oneOf([
                'absolute',
                'fixed'
            ]).isRequired,
            top: PropTypes.string,
            left: PropTypes.string,
            bottom: PropTypes.string,
            right: PropTypes.string,
            width: PropTypes.string.isRequired,
            height: PropTypes.string.isRequired
        }).isRequired
    };

    constructor(props) {
        super(props);
    }

    onJSBridge(...args) {
        console.log(this);
        console.log(args);
    }

    render() {
        const { style } = this.props;

        return (
            <div className="player-container" style={style}>
                <ReactSWF
                    src={'/player/GrindPlayer.swf'}
                    id={'player'}
                    ref={'player'}
                    name={'player'}
                    width={style.width}
                    height={style.height}
                    wmode={'transparent'}
                    flashVars={{javascriptCallbackFunction: this.onJSBridge}} />
            </div>
        );
    }
}

const select = state => state.player;

export default connect(select)(Player);
```

method onJSBridge allways call in window context. But if I pass flashVars={{javascriptCallbackFunction: this.onJSBridge.bind(this)}} I see error:

```Uncaught SyntaxError: Unexpected identifier``` in console

How could I call method of object?

**Comment by syranide** [comment]
See #9

ReactSWF is not involved in this and there's nothing ReactSWF can do that isn't opinionated/intrusive and would require special code built into the SWF.

Flash Player can only call functions exposed on window, so you're left with two choices:
1. Each instance should store a uniquely named function on `window`, say `my_swf_cb_123456()`. Then pass the function name in flash-vars to the SWF.
2. Export a named function on `window` with an extra ID parameter, say `my_swf_cb(id)`. Each instance should generate a unique ID and store the ID and instance in a map used by `my_swf_cb`. Then pass the ID in flash-vars to the SWF.

I'm refactoring ReactSWF a bit and I may end up providing this functionality through a separate complementary module, but this is not something ReactSWF should provide.

**Comment by syranide** [comment]
Hmm... it could make sense to have ReactSWF detect functions passed in flash-vars and special-case them perhaps. I'll think about this.

**Comment by syranide** [comment]
Oh right https://github.com/facebook/react/issues/4000 prevents this from being a good idea at the moment.

**Comment by syranide** [comment]
```js
// ExternalInterface calls should be routed through a callback bridge.
var nextSWFEICallbackID = 0;

class MyComp extends React.Component {
  handleSWFEICall() {
    console.log('SWFEICall', arguments);
  }

  componentWillMount() {
    // Caution: For most purposes nextSWFEICallbackID is sufficient. However, if
    // you rely on non-sequential server rendering you must generate GUIDs that
    // are deterministic per React root to avoid markup mismatch.
    this.SWFEICallbackName = '__MyComp_SWFEICallback_' + nextSWFEICallbackID++;
    window[this.SWFEICallbackName] = this.handleSWFEICall.bind(this);
  }

  componentWillUnmount() {
    delete window[this.SWFEICallbackName];
  }

  render() {
    return (
      <ReactSWF
        ...
        flashVars={{myCallbackName: this.SWFEICallbackName}}
      />
    );
  }
}
```

I'll publish this as an example in the readme soon.

**Comment by tadjik1** [comment]
thanks a lot!
