### ISSUE TITLE
Can't interact with SWF

### ISSUE THREAD

**Issue by mraak** [syranide/react-swf#18]
I really have the simplest possible example. SWF shows, but I can't click anything on it. Any ideas?

```
import React, { Component } from 'react';
import './App.css';
import ReactSWF from 'react-swf'

class App extends Component {
  render() {
    return (
      <div className="App">
        <ReactSWF
          src="MFD1.swf"
          id="mfd1"
          width="500"
          height="700"
          wmode="transparent"
        // flashVars={{ foo: 'A', bar: 1 }}
        />
      </div>
    );
  }
}

export default App;

```

**Comment by syranide** [comment]
The SWF doesn't register clicks as it should? That has never occured to me, you sure there isn't a bug in your SWF code? Could always try without wmode transparent, maybe there's a bug.

**Comment by mraak** [comment]
Nope, that didn't fix it. 

My SWF works normally as standalone or when embedding it through the standard object tag. At some point I will try to do a simplified example I thought you might have a solution at hand. It would be good if you added a working example or a test to repo.

**Comment by syranide** [comment]
@mraak I've never encountered anything like this and ReactSWF simply creates the same object tag for you, you're example itself is fine and there's nothing more to it. Are you sure there's nothing blocking the SWF, say a div? If you use the developer tools and click there, does it actually highlight the SWF-node and not some other node?

I'm assuming you're not ExternalInterface in the SWF?

**Comment by mraak** [comment]
Oh the SWF does use the ExternalInterface is that's what you mean. 

This is the DOM, and it displays nicely, just not being able to interact.

![image](https://user-images.githubusercontent.com/812714/33378473-2b7d8530-d515-11e7-998c-00975df16bcb.png)

**Comment by syranide** [comment]
If it's interaction with ExternalInterface that is getting ignored for you then it's likely that you're interacting with ExternalInterface before/without `addEventListener(Event.ADDED_TO_STAGE, ...)`. This is incorrect but will not always surface. React handles the DOM differently and I believe it would trigger this edge-case, so you have to make sure you execute all your code inside the `ADDED_TO_STAGE` callback and immediately in `Main`.

Anyway, if you connect the debugger to the SWF this should be obvious.

**Comment by mraak** [comment]
The problem is still the SWF not detecting the mouse overs and mouse clicks. ExternalInterface is being used but I'm not yet so far into testing. Also the SWF seems to be loading and updating the data from the internet successfully, it's just mouse interactions that are not working.

**Comment by syranide** [comment]
Very strange, I have no idea what could cause that. It could possibly be some edge-case with React and object-nodes. Have you attached the SWF debugger and made sure there's no exceptions in your code?

**Comment by mraak** [comment]
I've no idea how to do that, but as I said the SWF is working normally otherwise. React at the end renders the thing to completely normal HTML as far as I know, and that HTML looks perfectly OK for SWF to run. 

Could you maybe post a working example with some mouse interactions working, that way I'd be able to compare the two.

**Comment by syranide** [comment]
React creates nodes individually and not using `innerHTML` (like with static HTML) and this affects the SWF runtime in certain ways. One being that the ExternalInterface is only available after `ADDED_TO_STAGE` and will throw exceptions before that. So only guess is that you're interacting with the ExternalInterface before it's ready, it throws and exception and stops execution and thus prevents your mouse listeners from being attached and working.

I would recommend that you install the flash debug runtime from the Adobe page, this will allow you to see any exceptions that happens.

**Comment by SuryLeo** [comment]
Hi syranide,
Glad that you have posted this react-swf component and its really useful. Need some help on this. Could you please upload one end to end example which really helps many people like me.  We are not sure how to use this.  So please help us by posting one working example....... We appreciate your help on this.

Thank you....

**Comment by syranide** [comment]
> Could you please upload one end to end example which really helps many people like me.

@SuryLeo What do you mean exactly? There are two examples in the repository readme, one being the general use-case of just rendering an SWF (you really just need to set `src` and width+height). If you want to interact with it via JS or ExternalInterface then you need to look at the second example, but there's no "right way" of doing it and depends on the needs and circumstances.

Also know that ReactSWF is basically just a replacement for the traditional "swfobject" library, i.e. it inserts it an SWF into the DOM. How you then interact with the SWF is out of reach of ReactSWF and whatever information you find on the internet applies to ReactSWF as well.
