### ISSUE TITLE
Problem using in React Native: View config not found for name

### ISSUE THREAD

**Issue by lxylinki** [syranide/react-swf#19]
![Screenshot_1558055259](https://user-images.githubusercontent.com/4198567/57896410-3b277000-7883-11e9-82c4-1c0dd9d6144a.png)

**Comment by lxylinki** [comment]
This error occur also after I changed component name to capital.

**Comment by syranide** [comment]
Just for posterity, as I mentioned over email. ReactSWF is for ReactDOM, not ReactNative. So AFAIK there's no solution.
