### ISSUE TITLE
"ReferenceError: React is not defined" when building with browserify.

### ISSUE THREAD

**Issue by sesm** [syranide/react-swf#4]
A distilled example can be found here: https://github.com/sesm/reactswf-build-issue
To reproduce the issue:
> $npm install
> $npm run build
> Open main.html in browser

Expected: \<object\> tag appears on the page.
Observed: "ReferenceError: React is not defined" in JS console.

This issue can be fixed by adding a line
>var React=require('react');

to the top of react-swf.js, but I'm not sure it's the right way to fix the problem since I'm not yet familiar enough with NPM module system.

**Comment by sesm** [comment]
I figured out that requiring react via CommonJS syntax is the right thing to do for npm module.

**Comment by syranide** [comment]
Oh wow * *facepalm* *.

Yeah, there should be a `var React = require('react');` in the npm-version, it got lost in translation I never noticed. I'll have this fixed and published later today.

Thank you!

**Comment by syranide** [comment]
I got it done right away instead, 0.9.6 published.

Thanks again!
