### ISSUE TITLE
Not Triggering Firefox ExternalInterface Callback

### ISSUE THREAD

**Issue by andrewburgess** [syranide/react-swf#8]
I'm not sure of the best way to get you a minimal example to demo this, but embedding a Flash movie in Firefox doesn't seem to trigger ExternalInterface callbacks, nor can I call exposed methods from the Flash movie.

The SWF I'm using is from here: https://github.com/mangui/flashls/blob/dev/bin/debug/flashlsChromeless.swf

I have a component with the following relevant methods:
```
componentWillMount() {
    window.VideoPlayer = window.VideoPlayer || {};
    window.VideoPlayer[this.props.video.id] = {
        callback: _.bind(this.flashCallback, this)
    };
}

componentDidMount() {
    this.$plugin = this.refs.flash.getFPDOMNode();
}

render() {
    let vars = {
        callback: `window.VideoPlayer[${this.props.video.id}].callback`
    };

    return (
        <ReactSWF
            allowScriptAccess="always"
            flashVars={ vars }
            id={ `videoPlayer_${this.props.video.id}` }
            key={ `videoPlayer_${this.props.video.id}` }
            ref="flash"
            src="/assets/flash/VideoPlayer.swf"
            wmode="transparent"
        />
    );
}

flashCallback(event, args) {
    this.log.debug({ args }, `Flash Player :: ${event}`);

    if (_.isFunction(this[`on${eventName}`])) {
        this[`on${eventName}`].apply(this, args);
    }
}
```

This all works correctly in Chrome at the very least. Firefox doesn't seem to ever call the callback, nor can I call `this.$plugin.methodOnFlashMovie()` like I would expect.

**Comment by syranide** [comment]
I have a project myself in which I rely heavily on ExternalInterface and it works across all browsers, including FireFox, and there is no special code in ReactSWF for ExternalInterface other than `getFPDOMNode()` for returning a reference to the actual node.

So all I can really say at this point is that it's probably something on your end... perhaps you could check that `ExternalInterface.available` really is `true`? Could it be that you're adding the callbacks before `Event.ADDED_TO_STAGE` has occured?

**Comment by andrewburgess** [comment]
Alright, I'll see if I can pull the SWF source and try debugging it. I know that the SWF works in Firefox from here: http://www.flashls.org/latest/examples/chromeless/ but it seems to be using the old `<object><embed /></object>` style of adding flash embeds.

**Comment by andrewburgess** [comment]
:rage: so it seems that Firefox doesn't like loading flash files from `localhost`. I deployed to our development server and it loads just fine.

Sorry for the false alarm

**Comment by syranide** [comment]
No problem :)

You may be able to work around that in the SWF by allowing script requests from all hosts (`*`) via some system function somewhere. But I'm not entirely sure.
